<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJxkxfvm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxkxfvm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJxkxfvm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJxkxfvm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJxkxfvm\appDevDebugProjectContainer([
    'container.build_hash' => 'Jxkxfvm',
    'container.build_id' => '236693a8',
    'container.build_time' => 1572535376,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxkxfvm');
